-- Creates APPLY_COMPLIANCE_TAGS stored procedure.

-------------------------------------------------------------------------------------------------------
--- TODO - TEMPORARY UNTIL DATA SERVICES CAN CREATE NEW TAGS IN DB_DS_AUTOMATION.PUBLIC SCHEMA
USE ROLE ROLE_SNFLK_DEPT_ENTARCH_MGR_NP;

CREATE OR ALTER DATABASE DB_ARCH_AUTOMATION COMMENT='Temporary definitions of shared objects proposed by architecture until they can be  moved into DB_DS_AUTOMATION schema';
CREATE OR ALTER SCHEMA DB_ARCH_AUTOMATION.GOVERNANCE;

CREATE OR ALTER TAG DB_ARCH_AUTOMATION.PUBLIC.PAYX_UNMASK_DATABASE_ROLE;
GRANT APPLY, READ ON TAG DB_ARCH_AUTOMATION.PUBLIC.PAYX_UNMASK_DATABASE_ROLE TO ROLE PUBLIC;

CREATE OR ALTER TAG DB_ARCH_AUTOMATION.PUBLIC.PAYX_SEMANTIC_TYPE;
-- PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;
-- TODO: Operate PROPAGATE property requires APPLY TAG ON ACCOUNT privilege.
GRANT APPLY, READ ON TAG DB_ARCH_AUTOMATION.PUBLIC.PAYX_SEMANTIC_TYPE TO ROLE PUBLIC;

-- "PAYX_SENSITIVE-DATA-TYPE" is defined in DB_DS_AUTOMATION, but data services has not granted APPLY privileges on this yet
CREATE OR ALTER TAG DB_ARCH_AUTOMATION.PUBLIC."PAYX_SENSITIVE-DATA-TYPE";
GRANT APPLY, READ ON TAG DB_ARCH_AUTOMATION.PUBLIC."PAYX_SENSITIVE-DATA-TYPE" TO ROLE PUBLIC;
